### ISSUE TITLE
illegal base64 data at input byte 2 - exit status 1

### ISSUE THREAD

**Issue by ChemicalXandco** [outersky/har-tools#13]
I've probably done something wrong! Please help.

**Comment by outersky** [comment]
Would you please give more details or the sample har file, thanks.

**Comment by ChemicalXandco** [comment]
Ok so I'm windows 8.1 64bit. I used `go run harx.go -x <out_directory> <example.har>` but with the right directories. I'm a bit of a noob but I know how the command prompt works. The harx.go was definitely running and I have the latest version of go.

[sketchfab.com.zip](https://github.com/outersky/har-tools/files/1404285/sketchfab.com.zip)

**Comment by outersky** [comment]
fixed: output ecmascript as text now.
