### ISSUE TITLE
Create builds by github releases

### ISSUE THREAD

**Issue by AlexKalinin** [outersky/har-tools#14]
![image](https://user-images.githubusercontent.com/1572839/63835659-57ae6a80-c991-11e9-821f-01178fb32ca5.png)

Not everybody has installed GoLang in his system
I builded my one, but it would be faster to use already builded binary file. 

My binary file, builded under osx 10.13.6:

[harx.zip](https://github.com/outersky/har-tools/files/3549654/harx.zip)

**Comment by clok** [comment]
Used this tool today and loved it. Hope the PR that I just posted helps the project. Happy to contribute! https://github.com/outersky/har-tools/pull/18
