### ISSUE TITLE
harx tries to base64 decode XML MimeType 

### ISSUE THREAD

**Issue by nikidimi** [outersky/har-tools#8]
Line 91 only checks for certain mime types before deciding whether to use base64 or not
if strings.Index(c.MimeType, "text") != -1 || strings.Index(c.MimeType, "javascript") != -1 || strings.Index(c.MimeType, "json") != -1 {

I think it will be better to check the "encoding" field instead of the "mimeType", because it is difficult to check for every possible type.
In my case, I have a DASH manifest file in my HAR file, mimeType "application/dash+xml" and it is not base64 encoded, but harx tried to base64 decode it.

**Comment by outersky** [comment]
fixed for version 1.2 har files where encoding is introduced in.
